In [22]:
import numpy as np
num=np.array([1,2,3,4])
print("The 1 dimensional array is:")
print(num)
print("multiplied by 2 for num1=",num*2)
print(num+10)
num1=np.array([5,6,7,8])
add=num+num1
print(add)

The 1 dimensional array is:
[1 2 3 4]
multiplied by 2 for num1= [2 4 6 8]
[11 12 13 14]
[ 6  8 10 12]


In [27]:
num3=np.array([[1,2,3],[1,2,3]])
num4=np.array([[6,7,8],[9,10,11]])
sub=num4-num3
print(sub)

[[5 5 5]
 [8 8 8]]


In [28]:
num4=np.array([[[6,7,8],[9,10,11],[12,13,14]]])
print(num4.ndim)

3


In [29]:
import numpy as np
num4=np.array([[[6,7,8],[9,10,11],[12,13,14]]])
num5=np.array([[[2,3,4],[5,6,7],[7,8,9]]])
print(num4.dtype)
div=num4/num5
print(div)

int64
[[[3.         2.33333333 2.        ]
  [1.8        1.66666667 1.57142857]
  [1.71428571 1.625      1.55555556]]]


In [30]:
x=np.zeros([1,1])
print(x)

[[0.]]


In [31]:
x=np.zeros([3])
print(x)

[0. 0. 0.]


In [32]:
x=np.full((2,2),10)
print(x)
print(x.ndim)

[[10 10]
 [10 10]]
2


In [33]:
x=np.arange(10,100)
y=np.arange(110,200)
print(x)
print(y)
op=x*y
print(op)
print(x.ndim)
print(y.ndim)
print("dim=",op.ndim)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199]
[ 1100  1221  1344  1469  1596  1725  1856  1989  2124  2261  2400  2541
  2684  2829  2976  3125  3276  3429  3584  3741  3900  4061  4224  4389
  4556  4725  4896  5069  5244  5421  5600  5781  5964  6149  6336  6525
  6716  6909  7104  7301  7500  7701  7904  8109  8316  8525  8736  8949
  9164  9381  9600  9821 10044 10269 10496 10725 10956 11189 11424 

In [34]:
x=np.arange(10,100)
y=np.arange(110,200)
print(x.ndim==2)
print(y.ndim==2)
op=x*y

False
False


In [12]:
import numpy as np
x = np.array([1,2,3]).reshape(1,3)
print(x)
print(x.ndim)

[[1 2 3]]
2


In [13]:
x=np.arange(1,26).reshape(5,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
x=np.arange(1,101).reshape(10,10)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [15]:
import numpy as np
import random
np.random.randint(10,20,8)

array([14, 13, 19, 13, 19, 10, 10, 11])

In [16]:
import numpy as np
import random
np.random.random(100)

array([0.07987046, 0.10800744, 0.66820796, 0.73180547, 0.59727805,
       0.9729524 , 0.21692654, 0.07430472, 0.23092837, 0.04210256,
       0.36387962, 0.55024951, 0.6536098 , 0.90849984, 0.05074218,
       0.17330022, 0.42105438, 0.94081832, 0.09774169, 0.14154947,
       0.8907479 , 0.96346005, 0.6593832 , 0.32725161, 0.42293311,
       0.23349213, 0.02024718, 0.03472925, 0.5436221 , 0.69138549,
       0.88416277, 0.0575657 , 0.95373995, 0.52601031, 0.10575745,
       0.68121075, 0.59422959, 0.98141864, 0.88711037, 0.29967217,
       0.03082676, 0.9568437 , 0.9089234 , 0.85622615, 0.11346895,
       0.66361102, 0.12266079, 0.7427863 , 0.32549927, 0.37179573,
       0.34603469, 0.13251994, 0.68288561, 0.92406899, 0.07330392,
       0.19765808, 0.74654851, 0.98846836, 0.13034305, 0.16010589,
       0.92478079, 0.97477848, 0.51750189, 0.95530279, 0.68647984,
       0.41611418, 0.99986904, 0.96589798, 0.31628674, 0.0417112 ,
       0.9689503 , 0.27128818, 0.25721839, 0.99731763, 0.19463

In [17]:
matrix = np.array([[1, 2],[3, 4]])
print(matrix)
print("shape=",matrix.shape)
print(matrix.T)
print(matrix.dtype)

[[1 2]
 [3 4]]
shape= (2, 2)
[[1 3]
 [2 4]]
int64


In [18]:
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
a=np.array([1,2,3,4])
print(a*2)
print(a+10)

[2 4 6 8]
[11 12 13 14]


In [21]:
num=np.array([[1,2,3],[1,2,3]])
num1=np.array([[6,7,8],[9,10,11]])
add=num+num1
print(add)

[[ 7  9 11]
 [10 12 14]]
