In [1]:
!pip install numpy

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr[1])
print(arr[3])
print(arr[2]+arr[3])

[1 2 3 4]
2
4
7


In [4]:
ar=np.array(23)
print(ar)
print(ar.ndim)

23
0


In [5]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
print(ar)
print(ar.ndim)


[[1 2 3 4]
 [5 6 7 8]]
2


In [6]:
ar=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar)
print(ar.ndim)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.ndim)

print(arr[0, 1])


2
2


In [11]:
ar=np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(ar[0,1])
print(ar.ndim)

[1 2 3 4 5]
3
