In [2]:


#sorting
import numpy as np
array=np.array([[-1,2,3,4],[1,6,0,-1],[10,12,1,3]])

array.sort(axis=1)
print(array)


[[-1  2  3  4]
 [-1  0  1  6]
 [ 1  3 10 12]]


In [5]:
#concatenation of 1D arrays
array1=np.array([1,2,3,4,5])
print(array1)
array2=np.array([6,7,8,9,10])
#print(array1)
print(array2)
print(np.concatenate((array1,array2)))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#concatenation of 2D arrays
array1=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
array2=np.array([[6,7,8,9,10],[6,7,8,9,10],[6,7,8,9,10]])
print(np.concatenate((array1,array2),axis=0))

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]


In [7]:
#Reshaping the arrays
array=np.arange(10,30)
array.size
print(array)
array.reshape(2,10)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [8]:
#statistical operations on array
#max
array=np.array([1,2,3,4,56,-1,60,92,0])
s=array.max()
print(s)
a=array.min()
print(a)
array2=np.array([[1,2,3,4],[5,6,7,8],[10,30,40,670]])
print(array2)
print(array2.max())
print(array2.min())

92
-1
[[  1   2   3   4]
 [  5   6   7   8]
 [ 10  30  40 670]]
670
1


In [9]:
#min
array=np.array([1,2,3,4,56,-1,60,92,0])
array.min()
array2=np.array([[1,2,3,4],[5,6,7,8],[10,30,40,670]])
print(array2)
print(array2.min())

[[  1   2   3   4]
 [  5   6   7   8]
 [ 10  30  40 670]]
1


In [10]:
#sum function
array1=np.array([1,2,3,4,5,6,7,8,9,10])
print(array1.sum())
array2=np.array([[1,2,3,4],[5,6,7,8],[10,30,40,670]])
print(array2)
print(array2.sum(axis=0))

55
[[  1   2   3   4]
 [  5   6   7   8]
 [ 10  30  40 670]]
[ 16  38  50 682]


In [11]:
#mean fun ction
array1=np.array([1,2,3,4,5,6,7,8,9,10])
array1.mean()
array2=np.array([[1,2,3,4],[5,6,7,8],[10,30,40,670]])
print(array2)
array2.sum()
x=array2.sum()/12
print(x)
print(array2.mean(axis=1))

[[  1   2   3   4]
 [  5   6   7   8]
 [ 10  30  40 670]]
65.5
[  2.5   6.5 187.5]


In [ ]:
np.genfromtxt('/content/Marks.txt',delimiter=',',dtype=int)

np.loadtxt('/content/Marks.txt',skiprows=1,delimiter=',',dtype=int)

In [13]:
array=np.array([1,-22,-3,4,5,-6])
array.sort()
print(array)

[-22  -6  -3   1   4   5]


In [14]:
array=np.array([[1,23,5,76,-8,9,6,5],[43,-5,7,5,43,-23,4,6]])
array.sort(axis=1)
print(array)

[[ -8   1   5   5   6   9  23  76]
 [-23  -5   4   5   6   7  43  43]]


In [15]:
x=np.array([[2,-3,6,4,5,60],[23,4,55,66,77,11]])
y=np.array([[24,15,13,14,2,30],[55,44,33,66,44,33]])
print(x)
print(y)
print(np.concatenate((x,y),axis=1))

print(np.concatenate((x,y),axis=0))
print(x.shape)
print(y.shape)

[[ 2 -3  6  4  5 60]
 [23  4 55 66 77 11]]
[[24 15 13 14  2 30]
 [55 44 33 66 44 33]]
[[ 2 -3  6  4  5 60 24 15 13 14  2 30]
 [23  4 55 66 77 11 55 44 33 66 44 33]]
[[ 2 -3  6  4  5 60]
 [23  4 55 66 77 11]
 [24 15 13 14  2 30]
 [55 44 33 66 44 33]]
(2, 6)
(2, 6)


In [16]:
import numpy as np
s=np.array([1,2,3,4,5])
print(s)

[1 2 3 4 5]


In [17]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
